apiVersion: v1
kind: Namespace
metadata:
  name: backend
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: password
---          
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend
  name: backend
  labels:
    app: backend
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/ferum-pdg/backend-api
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/ferum-pdg/backend-api:prod-latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: GROQ_API_KEY
        - name: QUARKUS_DATASOURCE_JDBC_URL
          value: jdbc:postgresql://postgres-svc:5432/postgres
        - name: QUARKUS_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: username
        - name: QUARKUS_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: password
---
apiVersion: v1
kind: Service
metadata:
  namespace: backend
  name: postgres-svc
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432          
---
apiVersion: v1
kind: Service
metadata:
  namespace: backend
  name: backend-svc
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: backend
  name: ferum-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: backend-svc
            port:
              number: 8080  