apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend
  name: backend
  labels:
    app: backend
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/ferum-pdg/backend-api
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/ferum-pdg/backend-api:prod-latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: GROQ_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  namespace: backend
  name: backend-svc
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: backend
  name: ferum-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-svc
            port:
              number: 80          